# Generated by Django 4.2 on 2026-06-11 12:03

import backend.apps.cart.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(default=backend.apps.cart.models.uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='购物车ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('item_id', models.CharField(default=backend.apps.cart.models.uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='购物车项ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='关联购物车')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='dishes.dish', verbose_name='关联菜品')),
            ],
            options={
                'verbose_name': '购物车项',
                'verbose_name_plural': '购物车项',
                'db_table': 'cart_item',
                'unique_together': {('cart', 'dish')},
            },
        ),
    ]
