# Generated by Django 4.2 on 2026-06-11 12:03

import backend.apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default=backend.apps.users.models.uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=20, verbose_name='昵称')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像URL')),
                ('role', models.CharField(choices=[('user', '普通用户'), ('merchant', '商家')], default='user', max_length=10, verbose_name='角色')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
