# Generated by Django 4.2 on 2026-06-11 12:03

import backend.apps.orders.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('total_orders', models.IntegerField(default=0, verbose_name='总订单数')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总收入')),
                ('preparing_count', models.IntegerField(default=0, verbose_name='备餐中')),
                ('waiting_pickup_count', models.IntegerField(default=0, verbose_name='待取餐')),
                ('completed_count', models.IntegerField(default=0, verbose_name='已完成')),
                ('cancelled_count', models.IntegerField(default=0, verbose_name='已取消')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
                'db_table': 'daily_stats',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(default=backend.apps.orders.models.generate_order_id, editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='订单号')),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('order_status', models.CharField(choices=[('pending_payment', '待支付'), ('preparing', '备餐中'), ('waiting_pickup', '待取餐'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending_payment', max_length=20, verbose_name='订单状态')),
                ('pick_up_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='取餐码')),
                ('pay_deadline', models.DateTimeField(default=backend.apps.orders.models.default_pay_deadline, verbose_name='支付截止时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.CharField(default=backend.apps.orders.models.uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='订单项ID')),
                ('dish_name', models.CharField(max_length=50, verbose_name='菜品名称(快照)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价(快照)')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='dishes.dish', verbose_name='关联菜品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '订单项',
                'verbose_name_plural': '订单项',
                'db_table': 'order_item',
            },
        ),
    ]
