# Generated by Django 4.2 on 2026-06-11 12:03

import backend.apps.payments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.CharField(default=backend.apps.payments.models.uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='支付ID')),
                ('pay_type', models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝')], max_length=20, verbose_name='支付方式')),
                ('pay_status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败')], default='pending', max_length=20, verbose_name='支付状态')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '支付',
                'verbose_name_plural': '支付',
                'db_table': 'payment',
            },
        ),
    ]
