# Generated by Django 4.2 on 2026-06-11 12:03

import backend.apps.dishes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.CharField(default=backend.apps.dishes.models.uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='菜品ID')),
                ('dish_name', models.CharField(max_length=50, verbose_name='菜品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('category', models.CharField(choices=[('recommended', '推荐'), ('signature', '招牌'), ('drinks', '饮品'), ('snacks', '小吃')], max_length=20, verbose_name='分类')),
                ('images', models.JSONField(blank=True, default=list, null=True, verbose_name='菜品图片列表(images[0]为主图)')),
                ('month_sales', models.IntegerField(default=0, verbose_name='月销量')),
                ('status', models.BooleanField(default=True, verbose_name='状态(1上架/0下架)')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
                'db_table': 'dish',
            },
        ),
    ]
